    name: Node.js CI Tests

    # Controls when the workflow will run
    on:
      # Triggers the workflow on push events but only for the main branch
      push:
        branches: [ main ] # Uncomment this if you want tests on pushes to main
      
      # Triggers the workflow on pull request events for the main branch
      pull_request:
        branches: [ main ]

      # Manual run from actions tab
      workflow_dispatch:

    jobs:
      test:
        # The type of runner that the job will run on
        name: Run unit tests
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout repository
            uses: actions/checkout@v4

          # Sets up Node.js environment
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20' # Use a version compatible with your project (e.g., 18, 20)
              cache: 'npm' # Cache npm dependencies

          # Installs dependencies using package-lock.json
          - name: Install dependencies
            run: npm ci

          # Runs the test script defined in package.json
          - name: Run tests
            run: npm run build